name: smart_kit
description: A Flutter Windows app for reading serial port data and plotting graphs
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_libserialport: ^0.6.0
  fl_chart: ^1.1.1
  path_provider: ^2.1.0
  file_picker: ^10.3.10
  cupertino_icons: ^1.0.2
  window_manager: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.3


flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/app_icon.png"

 

flutter:
  uses-material-design: true